### ISSUE TITLE
MFDB Data explorer using shiny

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#1]
Currently finding out why your query isn't returning any data is pretty annoying. It would be really nice if there was an R query builder that let you off/on restrictions to find data.

Once this exists, rgadget has a bunch of plots that would also be very useful to attach to this.

**Comment by bthe** [comment]
I suggest to close this issue and point users towards the dplyr commands.

**Comment by lentinj** [comment]
Either way I don't seem to be getting around to it immediately. Can re-open if I pick it up again.
