### ISSUE TITLE
Ability to store tow/station information

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#10]
Bjarki: "Would there also be possible to add a "stations" table, i.e. a table
that where I could put more detailed records on the sample such as
date, lat and lon, further details on the gear, depth, tow length,
etc."

**Comment by lentinj** [comment]
I guess it could be used for:-
- Getting a list of used tow IDs back when you make any of the existing queries, then separately requesting the data on that tow
- Querying by tow ID when generating Gadget files
- Getting all tow IDs that match some specification.

**Comment by lentinj** [comment]
Bjarki:
- This is exactly the type of information that is used to generate CPUE, if one were to calculate these using mfdb. 
- Specify a fleet based on a group of vessels instead of gear type to account for certain species targeting

Future use may extend to data on quota allocation (which is per company and vessel), but I haven’t really looked into this data yet.

**Comment by lentinj** [comment]
It was also noted that a tow ID would be useful anyway. Maybe tow_name like stomach_name?

**Comment by bthe** [comment]
For examples see:
- fjolst::stodvar (station list with detailed information on the samples)
- Logbooks::lina (net,botnv)  with detailed logbook info

**Comment by lentinj** [comment]
@bthe Storing tow date: Is this so you can go "Tows between 12/11/2010 -- 14/04/2011", or just so you can identify which tow you are looking at?

**Comment by bthe** [comment]
Identifying individual tows, currently I'm uploading logbook data as separate data type on tow by tow basis so the former functionality is already supported. One potential use would be to look at species mixtures, i.e. what species are actually caught together.

**Comment by lentinj** [comment]
Okay, for now I've added in a date (i.e. day-of-month) column to go with year and month in the `wip-4.x-2` branch. This might be more awkward to work with in some cases, but the information will be there at least.

Most of the tow table is there too, as you suggest at the top, still needs a script to exercise it though but I'll do that tomorrow morning.

**Comment by lentinj** [comment]
This is now done: https://github.com/mareframe/mfdb/blob/wip-4.x-2/demo/inttest-towdata.R

Also note that I've added in the ability to use tow_length as an abundance index, does this make sense (and/or is it worth expanding to other properties)? IIRC this is something @vbartolino wanted to do a while ago.

**Comment by bthe** [comment]
The usefulness of this could potentially be in:
- The use of tow_length to standardise the abundance/biomass index.
- Query the total kilometers towed per fleet/timestep combination for the fleet data files. 
- Create a CPUE index directly from the database. The CPUE values are often time effects estimated using a linear model where various bits of information on the vessels are used to filter out potential nuisance factors. In R speak this could be done with a command similar to:

> lm(catch ~ as.factor(time) + vessel + gear + tow_length, data) 

where the parameter estimate for time  (usually year or quarter factors) is the CPUE

**Comment by lentinj** [comment]
This has been picked up in #33
