### ISSUE TITLE
Gear vocabulary

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#14]
Use FAO?

**Comment by bthe** [comment]
This has been suggested by a gear specialist:
ftp://ftp.fao.org/fi/document/cwp/handbook/annex/AnnexM1fishinggear.pdf

**Comment by lentinj** [comment]
@bthe @vbartolino We could certainly use this vocabulary happily, the short codes from the existing vocab don't overlap (which is good in a way), would just swapping be okay, or do we need to try and map from the old to the new?

**Comment by bthe** [comment]
It is certainly possible to construct a mapping between the two vocabularies as the definition of gears is finer in the FAO handbook than currently implemented. Attached is a mapping from our internal gear codes to FAO and https://github.com/bthe/gadget-models/blob/master/mfdb-setup/mapping.txt has the mapping from the same internal codes to the current vocabulary. 
[icelandic_gear_mapping.xlsx](https://github.com/mareframe/mfdb/files/24044/icelandic_gear_mapping.xlsx)
