### ISSUE TITLE
Index abundance by age

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#15]
Many survey datasets (ie, bottom trawl survey from DATRAS) have length distribution and individual fish biological data on different tables, such as tables HL and CA in DATRAS.
HL contains the abundance by length for the entire haul
CA contains length, age, maturity, etc. of individual fish often from a subsample

To calculate indices of abundance by age it is necessary to link info from these two tables. Usually an age-length-key from CA is used to split the lengths in HL...

Can this be done with a single query in mfdb?

**Comment by lentinj** [comment]
Not entirely, I don't think.

So, if I understand you correctly, you're using CA to generate groupings for each age, presumably based on frequency within CA. For example, if samples of length 28 are of age 3, then any sample of length 28 go in group 3. Or maybe you'd get the most common age for a length group.

Once you have this then you could use `mfdb_interval` to split up `HL` data by these groups, the columns would be called length not age but renaming them is easy enough.

If I've got the right idea here, then I think it would be always 2 queries, one to generate the grouping, the other to query the data. We could make the process easier though.

**Comment by vbartolino** [comment]
To assign the most common age to each length group is not exactly what's needed here. In practice, we would need to split the abundance of each length group in HL according to the age frequency for that length in CA.
At the moment I'm achieving what I need with the following steps:
1) two extractions:
lenDist <- mfdb_sample_count(..., 'length', data_source="HL")
alk <- mfdb_sample_count(..., c('age','length'), data_source="CA")

2) some extra code to split 'lenDist' into ages based on 'alk'

3) import the outcome into a new (temporary?) table
mfdb_import_survey(..., data_source="ageDist", ...)

4) extract the age distribution from the new table
mfdb_sample_count(..., c('age'), data_source='ageDist')

As I can see it there are difficulties to make this process more automatic. For instance, an alk has often missing or under-represented lengths at the level of individual hauls. For this reason an alk is often calculated over several hauls (ie, a subdivision or part of it) to split lenDist at a haul level, but the most appropriate level is often different among surveys and areas.

Probably better leaving the individual users to deal with this.

**Comment by lentinj** [comment]
Yeah, there needs to be some informed decision in step (2), and I don't think you can avoid that. (3) and (4) could probably be done in R though, rather than sending the data to the database and back.

**Comment by vbartolino** [comment]
The only reason why I'm sending the data to the database and back is the benefit of having associated aggregation file and updated likelihood file

**Comment by lentinj** [comment]
Looking at this again, doing (3) and (4) should be really easy just in R. Essentially you need something like:-

```
attr((outcome of 2), 'age') <- list(age = age, ...)
```

If you still need to do this, do you want to have a look at the code next week?
