### ISSUE TITLE
Problem with age aggregation files

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#16]
When exporting a age-length distribution as a catchdistribution component I noticed that the age aggregation file was setup as the length aggregation files, i.e. as age intervals:

age1 1 2
age2 2 3

instead of the age group

age1 1 
age2 2 

which is the expected behaviour.

**Comment by lentinj** [comment]
What does the R code you are using look like?

**Comment by vbartolino** [comment]
it seems to work fine in our case. This is the agg.file we get from exporting age-length distribution as a catchdistribution:
; Generated by mfdb 3.1.0
age1    1
age2    2
age3    3
age4    4

**Comment by bthe** [comment]
Example code for this problem:

mdb<-mfdb('Iceland')
reitmapping <- read.table(
        system.file("demo-data", "reitmapping.tsv", package="mfdb"),
        header=TRUE,
        as.is=TRUE)
defaults <- list(
    area = mfdb_group("1" = unique(reitmapping$SUBDIVISION)),
    timestep = mfdb_timestep_quarterly,
    year = 1982:2015,
    species = 'COD')
aggdata <-
    mfdb_sample_count(mdb, c('age', 'length'),
                      c(list(sampling_type = 'IGFS',
                             age = mfdb_step_interval('age',by=1,from=1,to=12),
                             species='COD',
                             length = mfdb_interval("len", seq(0, 150, by = 4))),
                        defaults))

**Comment by lentinj** [comment]
The problem is that `mfdb_step_interval` assumes you're outputting a length aggfile. This is definitely a bug.

You could work around this by using `mfdb_group(structure(1:12, names= paste0('age', 1:12)))` for now

**Comment by lentinj** [comment]
https://github.com/mareframe/mfdb/commit/749a44a87d6a26a44b80df1e8365540e916308e9 should fix this
