### ISSUE TITLE
prey numbers doesn't accept NA

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#18]
I've noticed that mfdb_import_stomach() return an error when the field 'count' in the prey_data has some NA. Why? Given that we will likely look at the presence_ratio of a certain prey rather than its amount NA should be acceptable, correct?

**Comment by lentinj** [comment]
Yes, there's no reason to insist on count data. It was probably more of a copy-paste oversight than something with actual reasoning behind it.

From a data integrity point of view, it seems slightly odd that some counts aren't known. Is the data trying to represent "many"? Not really my problem, mind :)

**Comment by lentinj** [comment]
Done as part of 4.x
