### ISSUE TITLE
Restructure fleet/vessel columns

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#2]
The current `vessel` column should become `vessel_type`. The taxonomy is probably okay.

In addition, there should be `vessel_name`, which can have contents per-case-study. Or do we want to generalise to `data-label`?

**Comment by bthe** [comment]
Regarding this:
- This is certainly a vessel_type
- Taxonomy may change according to case study
- I think we should have vessel_id, that is the actual vessel, where the vessel information may change from time to time.

**Comment by lentinj** [comment]
> Taxonomy may change according to case study

i.e. vessel_type's taxonomy? Obviously the vessel_name will change per-case-study.

**Comment by bthe** [comment]
My thinking was that the vessel_type table has fairly arbitrary size classifications and they do not necessaraly correspond to the classification used by statistics Iceland (as a example).  But this of course may be structured differently.

**Comment by lentinj** [comment]
If the size grouping isn't useful, I'm tempted to remove it entirely, and have something similar to ICES' VESSL vocab (i.e. Commercial / Ferry / Research / Trawler...). Then store vessel information in a separate table, with name, absolute length, type, ... And length groupings can be defined as you query, like anything else.

**Comment by bthe** [comment]
Sounds reasonable

**Comment by lentinj** [comment]
@bthe This is also done in `wip-4.x-2`, here's an example of what you can do:

https://github.com/mareframe/mfdb/blob/wip-4.x-2/demo/inttest-vessel.R

Is there any extra metadata on vessels that you would want to store? I've been debating on and off whether I should add a "vessel_tags" (and "tow_tags") column, so you could add arbitrary information to both vessels and tows. Currently I've decided not to since most of the additional information was numeric and would be very hard to work with in this form, you're welcome to twist my arm though.

**Comment by bthe** [comment]
Looks good, I guess if the vessel is modified (sinks/changes in size) the recommend process would be a new vessel entry. Wrt other meta data I would suggest engine size (Power) and tonnage.

**Comment by lentinj** [comment]
> I guess if the vessel is modified (sinks/changes in size) the recommend process would be a new vessel entry.

Yes, although if the vessel ID is re-used in the data it would be possible to rename the old one.
