### ISSUE TITLE
Merging with GadgetR

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#21]
I've been meaning discuss this with you wrt Rgadget, i.e. merge the Rgadget and gadget related mfdb bits as there quite a lot of overlap in the file I/O functionality that I would certainly like to use from mfdb. It would be wicked if one could flexibly define a full model using something like the %>% commands used in dplyr akin to:

```
gadget_stock('codmat',age=4:12, length=4:120) %>%
    add_recruits(years=all, rec='#rec%s',age=1) %>%
    add_recruits(year=1995,age=8,rec='#mig.rec1995') %>%
    spawns_into('codimm') %>%
        .... some other bits
```

[i.e. https://github.com/smbache/magrittr]

**Comment by bthe** [comment]
Check out how the cod and haddock models are created using a combination of mfdb and Rgadget:
https://github.com/bthe/gadget-models
In particular look at 02-haddock/00-data/setup-model.R

**Comment by lentinj** [comment]
The key bit to fiddle around is both have a `gadget_dir_write`. There's a few differences:-
- It's a S3 generic in MFDB, an S4 method in GadgetR.
- In MFDB it updates all relevant files (i.e. aggfiles, likelihood files and the mainfile), in GadgetR it replaces the one file contents entirely.

How I think this should be approached:-
- Take out the `gadget_file` S3 class and it's reading/writing, copy it ~wholesale into gadgetR
- Rewrite the `rgadget::gadget_dir_write` methods to use the mfdb low-level file updating code, and to work in a manner more similar to `mfdb::gadget_dir_write`. I think the mfdb behaviour as above is preferable, and more useful.
- Keep the S4 classes in `gadgetClass.R`, convert the high-level functions, e.g. `gadget_likelihood_component` to use an S4 class.
  Any comments?

As for using `%>%` for stockfile generation bit-by-bit, that'd actually be pretty easy. Being compatible with the  `%>%` operator basically means a set of function that take the value from the last as their first parameter. Which is roughly what the functions already there do.

However, this technique wouldn't make sense for the likelihood files, where you really wouldn't want to be throwing around all the associated data in memory, you want to write the likelihood component out to disk, then move onto the next.

**Comment by lentinj** [comment]
@bthe Have a look at the notes at the top of https://github.com/lentinj/rgadget/blob/combine-mfdb-stock-support/R/gadgetStock.R, which describe how I think it could work.

I've not described any syntax to update parts of a component. But you could do `stock@spawning@spawnareas <- ...`. Doesn't fit into the `%<%` syntax, but you could have a wrapper if you really needed.

**Comment by lentinj** [comment]
(side note: I really think all the stock related bits on rgadget should be in the same file, rather than slicing by function (read/write/class creation, etc.))

**Comment by bthe** [comment]
This certainly looks like what I had in mind, and looks like it will be fairly extendible. I guess something similar could be done for gadget fleet and print files (see make.gadget.printfile and make.gadget.fleet) 

On a related note, I assume that this structure allows the user to define different gadget-directories and copy bits of the model between the folders. Something like:

> gadget_read_stock('stock',gd1) %>%
>      component('recruitment',data=some_new_recruits) %>%
>      gadget_dir_write(gd2)

Btw, I see you are planning to use a S4 class system for this, is there any reason for that?

**Comment by lentinj** [comment]
> This certainly looks like what I had in mind, and looks like it will be fairly extendible. I guess something similar could be done for gadget fleet and print files (see make.gadget.printfile and make.gadget.fleet)

Yup. Ideally we'd make the likelihood files consistent too, but before that there needs to be some thought about how to manage lazy loading (you don't want to load up all the result sets that a likelihood file refers to automatically, but it'd be nice if they didn't just turn into file references on save).

> On a related note, I assume that this structure allows the user to define different gadget-directories and copy bits of the model between the folders

Don't see why not.

> Btw, I see you are planning to use a S4 class system for this, is there any reason for that?

Keeping the coding style consistent with the rest of rgadget was the only reason. Technically I'm not sure it'll make much difference.

**Comment by lentinj** [comment]
> Keeping the coding style consistent with the rest of rgadget was the only reason. Technically I'm not sure it'll make much difference.

No, this is getting silly, think I need to rethink `gadgetfile` slightly and make everything subclass that S3 class. Something new to look at later :)

**Comment by lentinj** [comment]
Raised https://github.com/bthe/rgadget/pull/10 with some stockfile stuff.

**Comment by bthe** [comment]
Looks good, playing around with it for a bit and I have a few comments along the way:

> gadgetstock('codimm',gd$dir,missingOkay = TRUE) %>%
>  gadget_update('stock',
>                minage = 1,
>                maxage = 10,
>                minlength = 4,
>                maxlength = 130,
>                dl = 2) %>%
>  ## does"something" updates should also allow for other names, e.g. doesrenew -> recruitment etc..
>  gadget_update('doesgrow',  
>                ## 1) some error catching would be useful here to ensure that the inputs are valid
>                ## i.e. make sure that the variables declared are valid
>                ## 2) the following could be set as default values for this component, although 
>                ## one might want to add the the name of the stock to the variable (like 'codimm.Linf') 
>                growthfunction = 'lengthvbsimple',
>                growthparameters = c(linf='#Linf',k='( \* 0.001 #k)', '#walpha','#wbeta'),
>                beta='(\* 10 #bbin)', 
>                maxlengthgroupgrowth=15) %>%
>  gadget_update('stock',  
>                ## here it would be useful to be able to call parameters defined above akin to dplyr::mutate  
>                ## default value should be 0.2 repeated for all ages
>                naturalmortality = c(0.5,  0.35, 0.2, 0.2,  0.2, 0.2, 0.2, 0.2, 0.2, 0.3)) %>%
>  gadget_update('refweight',
>                ## would be useful to have an option to have just alpha and beta from the relationship 
>                ## W=alpha_L^beta 
>                ## also just supply a normal data.frame
>                data=data_frame(length=seq(4,130,2),mean=6.5e-6_length^3.07)
>                )

**Comment by lentinj** [comment]
Done most of this (in my rgadget fork), but have a few questions:

> Does"something" updates should also allow for other names, e.g. doesrenew -> recruitment etc.. `gadget_update('doesgrow',`

I was a bit wary of doing this, it then makes it harder to correlate the code to the GADGET user guide. However I've added aliases for when the gadget user guide uses a different name in the section heading to the actual component name.

```
## 1) some error catching would be useful here to ensure that the inputs are valid
## i.e. make sure that the variables declared are valid
```

I've now done this for component names, however I'm very wary about codifying all GADGET parameters and any interdependence. It could be done fairly easily, but then if you modify how GADGET reads data files in any way you then have to change this in 2 places, and make sure people have installed a matching version of rgadget to gadget. If you still want to do this then we can.

```
## 2) the following could be set as default values for this component, although 
## one might want to add the the name of the stock to the variable (like 'codimm.Linf') 
growthfunction = 'lengthvbsimple',
growthparameters = c(linf='#Linf',k='( * 0.001 #k)', '#walpha','#wbeta'),
beta='(* 10 #bbin)', 
maxlengthgroupgrowth=15) %>%
```

Should doesgrow default to 1, or just if you do set it to 1 you flil in the defaults? I've done the latter, the former is just tweaking the defaults.

```
gadget_update('stock',
## here it would be useful to be able to call parameters defined above akin to dplyr::mutate
```

TODO:

```
## default value should be 0.2 repeated for all ages
naturalmortality = c(0.5, 0.35, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3)) %>%
```

Is the step for the age groups always 1, i.e. the length of this vector is `maxage - minage + 1`? If so I've done this. If not what's the best way to work it out?

```
gadget_update('refweight',
data=data_frame(length=seq(4,130,2),mean=6.5e-6length^3.07)
)
## would be useful to have an option to have just alpha and beta from the relationship 
## W=alphaL^beta 
```

Done.

```
## also just supply a normal data.frame
```

Done this. `gadget_update('refweight', data = data.frame(length = c(2,4,6,8,10), weight = 11:15))`.

**Comment by bthe** [comment]
Brilliant. Regarding testing I would usually just call gadget, sort of when done with model building by running:

> callGadget(s=1, log='nameOfLogfile')

And digest the innards of the logfile to find the cause (if any) for the error. This could of course be wrapped in a more highlevel R-command.  

> Should doesgrow default to 1, or just if you do set it to 1 you flil in the defaults? I've done the latter, the former is just tweaking the defaults.

 I would suggest that doesgrow should default to 1, as this is a key functionality of Gadget. 

> Is the step for the age groups always 1, i.e. the length of this vector is maxage - minage + 1? If so I've done this. If not what's the best way to work it out?

Age is always in one year increments.

**Comment by lentinj** [comment]
```
gadget_update('stock',
## here it would be useful to be able to call parameters defined above akin to dplyr::mutate
```

I can't see a way of getting it as neat as `mutate`, but with inserting an eval() you could do `gadget_update('stock', minage = 2, maxage = quote(minage + 10))` (note the quote()). I'm not convinced this is particularly nice though.

**Comment by lentinj** [comment]
```
gadget_update('stock',
## here it would be useful to be able to call parameters defined above akin to dplyr::mutate
```

I can't see a way of getting it as neat as `mutate`, but with inserting an eval() you could do `gadget_update('stock', minage = 2, maxage = quote(minage + 10))` (note the quote()). I'm not convinced this is particularly nice though.

**Comment by lentinj** [comment]
Okay, bar some tests for importing MFDB data (and then fixing it when I find out it doesn't work) I think this is done. I think it's working quite well though, should we be looking at some other file types?

**Comment by bthe** [comment]
I haven't had time to fully test this, but yes I think the most common functionality is handled very well. I still haven't tested how you implement maturity (which I assume is fairly straightforward) and how one would update parts of the recruitment/initialnumber file. In the latter case I would assume something like a get_data/update_data statement would be useful. 

I do think we need similar functionality for fleet files, total catches or effort based on queries from mfdb and a list of stocks and respective suitability functions.

**Comment by lentinj** [comment]
> I still haven't tested how you implement maturity

Nothing particularly clever, the following would probably work.

```
gadget_update('maturation', maturityfunction = 'constantweight', maturityfile = gadgetfile("maturation.filename", components = list(list(maturestocksandratios = c(. . .), coefficients = c(. . .)))))
```

This could be tidied up by creating the extra gadgetfile internally, and you just provide all parameters to `gadget_update()`. Shall I?

> How one would update parts of the recruitment/initialnumber file

i.e. read / modify the data file? You could get at the data.frame directly with `gs$doesrenew$numberfile$components[[1]]`. What's a likely scenario when doing this?

**Comment by bthe** [comment]
> This could be tidied up by creating the extra gadgetfile internally, and you just provide all parameters to gadget_update(). Shall I?

Sounds good:)

> i.e. read / modify the data file? You could get at the data.frame directly with gs$doesrenew$numberfile$components[[1]]. What's a likely scenario when doing this?

Most often I edit the parameter formula for the population numbers, e.g. the multiplier to ensure the number of fish is in the correct order of magnitude. I'll experiment a bit by using gs$doesrenew$numberfile$components[[1]] and let you know.
