### ISSUE TITLE
Error when processing no data

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#22]
Trying to write a catchdistribution likelihood for a specific gear where there were no samples and mfdb gave me an error, rightfully so but not a very descriptive one as it was in the middle of a very long script:

Error in compare_cols(names(data), c("year", "step", "area", "age", "length",  : 
  Expected data to have columns 'year,step,area,age,length,number', not ''

I would like to propose a different handling of this situation:
- the function should issue a warning stating that no data were found in the input, the likelihood component should be named and leave the likelihood file untouched.

**Comment by lentinj** [comment]
Yeah, that makes a lot more sense :)
