### ISSUE TITLE
stomach data, prey count default 'c(1)' or 'NA'?

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#25]
For small and/or well digested preys it is not unusual to have their total weight in the stomach but not their actual number. In this case prey count in the stomach data should not be 1, but NA as default in mfdb_import_stomach.

I suppose this may have implications on how we query stomachs for preymeanweight and preymeanlength.

**Comment by lentinj** [comment]
I see your point about well digested prey. You should be able to at least import this data now, by the way, and use it with the mfdb_stomach_ratio function.

However I can't see what we can do to then work out preymeanweight and/or length. Surely if it's too tricky to count the prey, measuring them is going to be even harder?

**Comment by lentinj** [comment]
Feedback from parallel session:
- Make `count = NA` default (count not available is a more logical default in this situation than expecting individual samples)
- Copy `total_weight` logic from sample
