### ISSUE TITLE
database and tables summary

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#28]
is there a function to list all the tables names?

**Comment by lentinj** [comment]
Do you mean all `data_source` values in the database, or actual tables?

The former:-

```
> mfdb_sample_count(mdb, c('data_source'), list(data_source = mfdb_unaggregated()))
$`0.0.0.0`
  year step area data_source number
1  all  all  all     cod2000     12
```

The latter doesn't have any useful interface in MFDB itself, although you could do:-

```
> mfdb:::mfdb_fetch(mdb,
+     "SELECT table_name",
+     " FROM information_schema.tables",
+     " WHERE table_schema = '", mdb$schema, "'")
```

(using `:::` functions shouldn't be encouraged but if you're playing around that's fine).

If you're using `psql` to poke around with the database directly then `\dt` will give you available tables.

**Comment by vbartolino** [comment]
the first does exactly what I meant.
Thanks
\V

**Comment by lentinj** [comment]
No worries!

**Comment by nataliia-kulatska** [comment]
I found also other way to check for it:
library(RPostgreSQL)
dbListTables(mdb$db)
dbReadTable(mdb$db,"data_source")

Maybe useful for someone.

Nataliia
