### ISSUE TITLE
Use postgresql schemas to split case studies instead of case_study

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#29]
The `case_study_id` column was a terrible mistake.
- A predefined list of case studies isn't useful
- Gives major problems with sequences with the bulk export/import: https://github.com/mareframe/mfdb/issues/9
- Not being able to override all taxonomies is going to be a pain in the future.

First, add logic to choose the schema on startup (optionally importing data from the `public` schema).

Once this is done, see how much `case_study_id` can be removed.

**Comment by lentinj** [comment]
`separate-schemas`, to become MFDB 5.x, will solve this.

**Comment by mmrinconh** [comment]
Hi, I updated to MFDB 5.x and I was using `mdb_comp <- mfdb('Test', db_params=list(dbname="mf"))` and `mdb_comp <- mfdb('Ibera', db_params=list(dbname="mf"))` and they don't work now. It gives me this error: `Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid value for parameter "search_path": "ibera, pg_temp"
DETAIL:  schema "ibera" does not exist
)`
Could you help me please

**Comment by lentinj** [comment]
@mmrinconh are you switching to MFDB 5.x now, or have you been using 5.x for a while and now updating? What version of Postgresql do you have installed? You can check by running `psql --version`.

E-mailing the output of the following would also be useful:

```
pg_dump --schema-only -F custom mf > ibera.pgdump
```

However, I'm fairly sure I know what's going on so if it's a problem don't worry.

**Comment by mmrinconh** [comment]
Thanks @lentinj, I have just updated yesterday. The version of Postgresql is psql (PostgreSQL) 9.3.6.

**Comment by lentinj** [comment]
Assuming that https://github.com/mareframe/mfdb/commit/040ddbbcee0bb7a42168f572e44f3e59914ef2a4 fixed this, so closing. Feel free to re-open if it's not!
