### ISSUE TITLE
Catch per unit effort likelihood component

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#33]
I would like to propose a new export routine that calculates catch per unit effort (CPUE) based on logbooks. Catch per unit effort is in its simplest form:

CPUE<sub>t</sub> = C<sub>t</sub>/E<sub>t</sub>

where C is the total catch, E is an indicator for the total effort (towtime, days at sea etc.. ). This is of course a fairly crude estimator and in the case where we have structural changes in the fleet (e.g. gear changes) this can be fairly biased. To fix this people resort to regression analysis of the form:

log(C<sub>it</sub>) = α + β log(E<sub>it</sub>) + Y<sub>t</sub> + G<sub>i</sub> + V<sub>i</sub> + other factors + ε<sub>it</sub>

where the C<sub>it</sub> is the catch of vessel i at t, E<sub>it</sub> effort, G<sub>i</sub> gear effect, V<sub>i</sub> vessel effect and Y<sub>t</sub> the year effect which is taken as the CPUE. In the case of MFDB other factors would be other potential columns from the tow/vessel table.

To allow for a bootstrap from the database this regression needs to take place on the postgres side of MFDB. Tutor-web has slides showing the matrix calculus needed for this problem (http://tutor-web.net/stats/stats544.02/01). Note that factors, such a vessel id, are in linear regression as N-1 variables (where N is the number of different levels of the factor) each of them taking the value 1 when the factor is equal to that level. 

Also this might help: https://rosettacode.org/wiki/Multiple_regression

**Comment by vbartolino** [comment]
I like the idea as fishery logbook are available to certain extent to some of us.

Do you think it would be beneficial to implement the suggestion above within a sufficiently generic routine to derive in a similar way CPUE also from scientific surveys (ie several international surveys have known gear and vessel issues)?

**Comment by bthe** [comment]
I don't see why not, the proposed method is a generalization of the current survey indices routine.

**Comment by lentinj** [comment]
Sorry if I'm being dense, but I'm not getting the CPUE formulation above, and haven't been able to find much else useful-looking to read (I thought there was some tutor-web material on CPUE, but can't find it).
- Is it multivariate, and each Y<sub>t</sub>, G<sub>i</sub>, V<sub>i</sub> also has a β?
- There's missing brackets around the "log(E<sub>it</sub>) + Y<sub>t</sub> + G<sub>i</sub> + V<sub>i</sub> + other factors" (or at least a matrix with log(E<sub>it</sub>), Y<sub>t</sub>, G<sub>i</sub>, V<sub>i</sub> columns)?

I'm also guessing that C<sub>it</sub> isn't reflecting the dimensions of the variable, rather it's a 1-dimensional matrix that has catch for all i and t combinations.

It might be easiest to implement with pl/r first, to work out the interface then worry about getting rid of the dependency later. It'll more complicated than the current survey indicies functions, as I'm presuming you'll need to choose which tow variable is used for Effort(?), as well as choosing which extra tow columns to use as factors. Also, say I request CPUE for a year, does MFDB use all catch data for that year to generate CPUE, available data for that vessel, area? or just everything?

**Comment by bthe** [comment]
Sorry for the sloppy indexing:) 
C_{igt} is the catch of vessel i, with gear g at time t
E_{igt} is the effort or the tow duration at the same dimensions
Y_t is the year effect, i.e. an estimated constant for each year. This the variable we want to estimate
G_g is the gear effect (constant for each gear)
V_i is the vessel effect (constant for each vessel)

**Comment by bthe** [comment]
Regarding the functionality, I guess the best way would be to develope a general linear regression functionality in pl/sql and then worry about the functionality. I would guess all columns in the gear and vessel tables should be available, and I would like to be able to restrict the calculation to a certain area and time period.

**Comment by vbartolino** [comment]
To have the method sufficiently generalised should zero-inflation be accounted?
At the moment we are using zero-inflated models to get a year-effect on Baltic cod from bottom trawl surveys.

library(mgcv)
mod <- gam(count ~ s(lon,lat) + s(depth) + year, offset=stand, family=ziP(), data=dat)

**Comment by bthe** [comment]
It would certainly be nice to have this general functionality but bear in mind that to implement something like a gam model you will need a maximum likelihood procedure plus some sort of a spline smoother. This is far from trivial to implement in postgres and in these cases I guess it would be more robust to fall back on calling R.

**Comment by lentinj** [comment]
I agree with @bthe - this will disappear down a rabbit hole if we're not careful. But having the ability to do this via. R could well be useful.

**Comment by lentinj** [comment]
@vbartolino the `mfdb_sample_rawdata` could be useful in your example though, see https://github.com/mareframe/mfdb/commit/dc038fe341fe2d338e1bb52711a4ca98846460d5

Sure MFDB isn't being that helpful here, but I don't think there's any reasonable way to encode the model requirements into use in an aggregation function.

**Comment by bthe** [comment]
Coming back to this, I think it is more sensible to allow a more general approach using the `mfdb_dplyr_*`. To generate uncertainty estimates, the dplyr routines would need to be adapted to allow for the use of the spatial bootstrap, mimicking the `sample_n` function. I guess something like:
```
res <- mfdb_dplyr(sample) %>%
          mfdb_bootstrap(areas = bs.areas) %>%
          .... ## some further analyses
```
where `res` would be a single bootstrap replicate would be what I'm after. This would then be repeated a number of times to obtain the desired confidence intervals of whatever analysis you want to produce.

**Comment by lentinj** [comment]
If this is what you want to do, you could probably feed the results of ``mfdb_sample_rawdata`` into dplyr and it'd work quite nicely. Although there's a few bugfixes it needs before that's really true.

**Comment by lentinj** [comment]
FWIW ``wip-6.x`` fixes those bugs, although I'm not done changing the schema yet so don't try it on any useful databases.
