### ISSUE TITLE
Generate all likelihood file versions when bootstrapping

### ISSUE THREAD

**Issue by lentinj** [mareframe/mfdb#34]
When bootstrapping, it would be useful to generate each permutation of likelihood file:-

```
  Rgadget/run_boostrap.R
  main
   |- likelihood (the "main" or template likelihood file)
   |- likelihood.1 .2, .3, .4, ....
   |- data ("main" data that isn't bootstrapped)
       - file. ...
   |- bs.data (the bootstrap data variants)
       - file.%d....
```
- The "template" likelihood file can just be whatever is in the non-bootstrapped version
- No combinatorial explosions of bootstraps. Assume that if multiple likelihood components are being bootstrapped, then they are being bootstrapped the same number of times

**Comment by bthe** [comment]
You may find it useful to look at gadget.bootstrap from https://github.com/bthe/rgadget/blob/master/R/gadgetfunctions.R

**Comment by lentinj** [comment]
Can we consider this equivalent to model variants (https://github.com/mareframe/mfdb/issues/35)? The structure won't be exactly the same, probably something like:

```
   |- main (the "main" mainfile)
   |- likelihood (the "main" or template likelihood file)
   |- data ("main" data that isn't bootstrapped)
       - file. ...
   |- variant.bs1
       |- main (the mainfile for this variant)
       |- likelihood (the bootstrapped variant)
       |- data (the data files that vary )
           |- file.....
```

...but it's the same problem.

**Comment by lentinj** [comment]
Assuming the above restructuring is okay, then something like the following should work:

```
for(i in seq_along(bootstrapped_agg_data))  {
    var_dir <- variant_dir <- gadget.variant.dir(dir, variant_dir = paste0('bs.', i))
    gadgetlikelihood('likelihood', var_dir, missingOkay = TRUE) %>%
        gadget_update('catchstatstics', data = bootstrapped_agg_data[[i]]) %>%
        write.gadget.file(var_dir)
}
```

To properly consider this done there could be a helper to do the above, but I'm not sure it's worth it. To give yourself enough flexibility you'd need to specify pretty much everything in the above anyway. @bthe any opinions?

**Comment by bthe** [comment]
This is more or less inline with what I was thinking, I'm playing around with this atm (see https://github.com/fishvice/gadget-models/tree/master/06-ling/00-setup). However it appears that 

a) `write.gadget.file` appends the bootstrap likelihood file to the variant main file 
b) `gadget_update` does not respect the variant directory, i.e. the path to the data file is not updated.

Solving a) is a bit of hack, I've added a `file_config` attribute named `mainfile_overwrite` that dictates whether or not the likelihood file should be appended. b) is a bit more elusive as Rgadget::gadget_update.gadgetlikelihood refers to mfdb::gadget_likelihood_component, but I assume somewhere the filename attribute should be edited.  Any pointers on how I can elegantly solve this?

**Comment by bthe** [comment]
My latest upload to Rgadget pretty much fixes b) (I hope). I added a path input to the print.gadgetfile function where, if one of the attributes of the path object was a variant.dir the printer would update the file paths accordingly.

**Comment by bthe** [comment]
I think this issue can be closed, see example uses on github.com/fishvice/gadget-models
