### ISSUE TITLE
Importing divisions fails

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#40]
I'm trying to import an additional division to areacells in mfdb from a data frame of the form:

```
> head(aug_reit)
     id  name     size lat lon subdivision
1 10535  1893 215.4353  30 -20       -2980
2 10509  -669 230.8233  29 -17       -3083
3 10491   833 222.3191  30 -17       -2983
4 10486  -676 232.5104  29 -17       -3083
5 10475   832 220.6048  30 -17       -2983
6 10460 -5408 260.4523  27  -5       -3295
```

using:

```
mfdb_import_division(mdb,
                     aug_reit %>% 
                       split(.$subdivision) %>% 
                       purrr::map('name'))
```

which results in a rather cryptic error:

```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  duplicate key value violates unique constraint "division_pkey"
DETAIL:  Key (division_id)=(84) already exists.
)
```

So two things really:
a) what am I doing wrong? 
b) would it be possible to feed a data frame directly into this function instead of splitting the data frame to a list?

**Comment by lentinj** [comment]
mfdb_import_division() is a somewhat odd anomaly in comparison to the rest of the import routines, it could do with some love.

> a) what am I doing wrong? 

The internal `division_id` is auto-numbered (i.e. postgres has a sequence that returns increasing values to use here). Somehow the sequence has diverged from reality. Try this from a psql prompt:

```
SELECT MAX(division_id) FROM iceland.division;
ALTER SEQUENCE iceland.division_division_id_seq RESTART WITH (the maximum from the above statement);
```

Replace "iceland" with the (lower case) case study name if it's different.

> b) would it be possible to feed a data frame directly into this function instead of splitting the data frame to a list?

There's no support for this currently, but given it's re-working to a data.frame internally then it's an easy change, and would make it match the other import functions. I'll look into this later today.

**Comment by bthe** [comment]
Thanks, this solved a) :)

**Comment by lentinj** [comment]
In an ideal world we ditch the division, and instead divide up areacells into groups, like we do with institute / country. This would get rid of the special case, and then mean you can import the data.frame of both areacells/divisions.

The main problem is divisions can currently overlap, and we'd be removing this ability. Is this bad? Or actually useful? There is a note in the old mfdb trello saying "Overlaps in areas: should check there aren't any".

**Comment by lentinj** [comment]
https://github.com/mareframe/mfdb/commit/dd153acf02a01fcb90fc0ca05e7eec8931226861 fixes (b), you can now provide the division with `mfdb_import_area()`, e.g.:

```
    mfdb_import_area(mdb, data.frame(
        name = c('45G01', '45G02', '45G03'),
        division = c('divA', 'divA', 'divB'),
        size = c(10,200,400)))
```

...so aug_reit could be imported with just some columns renamed. I've reworked all the examples to do it this way, since there's not much point using a separate `mfdb_import_division` call unless you want overlapping divisions.

There's no behind-the-scenes DB changes here, it'd still be nice to do the above. However, can keep the MFDB interface the same.
