### ISSUE TITLE
No temperature relation found in schema

### ISSUE THREAD

**Issue by pfrater** [mareframe/mfdb#41]
When creating a new schema using `mfdb('schema-name')` the temperature relation does not appear. It shows up in the public schema, but if I type `\dt iceland.temperature` (or another schema name) I receive the following:

ERROR:  relation "iceland.temperature" does not exist
LINE 1: select \* from iceland.temperature;

I therefore cannot import any temperature data.

**Comment by lentinj** [comment]
Is this locally or on the mfdb server?

**Comment by pfrater** [comment]
Locally. I haven't tried anything on the server since last Thursday. Also, I should note that a temperature relation is created in the Public schema; however, nothing gets imported there as you need a case-study name in `mfdb()`

**Comment by lentinj** [comment]
Okay, I've just pushed a fix, can you try that?

**Comment by pfrater** [comment]
Still no dice...

**Comment by lentinj** [comment]
As in it's still creating the temperature table for new schemas in the public schema?

**Comment by lentinj** [comment]
Actually I'm forgetting how this thing works. The temperature table was removed some time ago, and the data is now stored in `survey_index`. So public.temperature is probably a red herring.

What is the error you're getting when importing?

**Comment by pfrater** [comment]
Ah...okay. Yes, I see the temperature data in survey_index. Would I then just use `mfdb_survey_index_total()` to get the temperature back out? `mfdb_temperature()` doesn't seem to do it.

**Comment by lentinj** [comment]
`mfdb_temperature()` is just an alias for `mfdb_survey_index_mean()`, have a look at https://github.com/mareframe/mfdb/blob/5.x/R/mfdb_queries.R#L12

'course you can just use the mfdb_survey_index function directly. But I'm a bit confused as to why you're saying `mfdb_temperature()` isn't working.

**Comment by pfrater** [comment]
Nevermind...`mfdb_temperature()` is working fine. I think this was actually related to the other issue I opened and closed yesterday. I had the areacells wrong in my default params and therefore `mfdb_temperature()` couldn't do it's job properly. Since I couldn't find a temperature relation in mf I thought it was related to that.

Whew...so sorry to send you on a wild goose chase!!

**Comment by lentinj** [comment]
No worries!
