### ISSUE TITLE
mfdb_interval include lower tail of the data

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#43]
I'm currently setting up a model for ling which is a species that is hardly present in our surveys until the reach 30 cm or so (but can reach 180 cm easily). But there are the occasional fish below 30 cm every now and then. The model I'm setting up is species starts at 30 cm and ends in 160 cm. So I query the database using:
```
aggdata <- mfdb_sample_count(mdb, c('age', 'length'), 
                             c(list(
                               sampling_type = 'IGFS',
                               length = mfdb_interval("len", 
                                                      c(0,seq(minlength+4, maxlength, by = 4)),
                                                      open_ended = TRUE)),
                               defaults))

attributes(aggdata[['0.0.0.0.0']])$age$all <- minage:maxage
attr(attributes(aggdata[['0.0.0.0.0']])$length$len0,'min') <- minlength
```
Note that I use the `open_ended` switch to include everything above 160, but I need to hack the lowest size class to be within model parameters. Would it be possible to add a switch to the mfdb_interval functions to include lowest?

Also, would it be possible to add a way to specify the age aggregation when you have a pure length frequency query in mfdb_sample_count? This tends to get rather complicated when doing a bootstrap.

**Comment by lentinj** [comment]
So something like ``mfdb_step_interval('len', 4, from = minlength, to = maxlength, open_ended = c('upper', 'lower'))``? That's not a huge deal to sort out.

> Also, would it be possible to add a way to specify the age aggregation when you have a pure length frequency query in mfdb_sample_count?

Do you have an example to clarify this a bit? You can add the age aggregation to ``mfdb_sample_count`` regardless, in which case it will just filter the length results to anything within those ages. I'm not sure what else the age aggregation would do if you're not including the age output in the query.

**Comment by bthe** [comment]
> So something like mfdb_step_interval('len', 4, from = minlength, to = maxlength, open_ended = c('upper', 'lower'))? That's not a huge deal to sort out.

That would be ideal.

>  Do you have an example to clarify this a bit? You can add the age aggregation to mfdb_sample_count regardless, in which case it will just filter the length results to anything within those ages. I'm not sure what else the age aggregation would do if you're not including the age output in the query.

Yes, when I'm querying the length distributions there is little to no age data assigned to the entry, so querying an age range would simply discard the non-aged entries. But this might be solved simply by using something like `age=mfdb_interval(c(3,12),open_ended=c('lower','upper'))`

**Comment by lentinj** [comment]
@bthe Does https://github.com/mareframe/mfdb/commit/1a3a1996abaed99a5d1bff0d4c07b2210b862a20 sort you out?

**Comment by bthe** [comment]
This indeed does the trick, I now simply query the data without needing to manually edit the aggregation metadata:

```
ldist.igfs <-
  mfdb_sample_count(mdb, 
                    c('age', 'length'), 
                    c(list(
                      data_source = 'iceland-ldist',
                      sampling_type = 'IGFS',
                      age = mfdb_interval("all",c(minage,maxage),
                                       open_ended = c("upper","lower")),
                      length = mfdb_interval("len", 
                                             seq(minlength, maxlength, by = dl),
                                             open_ended = c("upper","lower"))),
                      defaults))
```

Note that the query above additionally sets the upper and lower bounds for age, while asking only for length distribution data (i.e. samples without age). I used the convention of setting age to be 0, when NA, on uploading to the database which I assume makes this possible.

**Comment by bthe** [comment]
Aaa, a bit quick to respone. This almost does the trick. `open_ended` does not behave exactly as I would expect. For instance when querying all fish measurements between 100 and 160 with `open_ended` set as "upper":
```
  mfdb_sample_count(mdb, 
                    c('length'),
                    c(list(
                      data_source = 'iceland-ldist',
                      sampling_type = 'IGFS',
                      length = mfdb_interval("len", c(100,160),open_ended = 'upper')),
                      defaults))
```
I get results aggregated into two groups, len100 (to 160) and len160 (and above), but I would expect to get only one group with the sum of the two groups.

**Comment by lentinj** [comment]
It'd work I think, but I'm confused as to why you don't just use ``age = NULL`` in the above.

**Comment by bthe** [comment]
The reason why I am fuzzing about the age aggregation when querying is that Gadget will need to have an age-aggregation file for the `catchdistribution` component.  Gadget will then produce predicted data based on the aggregation files to compare with the observations. This is the simplest way that I can think of to set these aggregations without editing the attributes of the data manually.

**Comment by bthe** [comment]
Fixed a couple of paper cuts in commit (https://github.com/mareframe/mfdb/commit/6991d9dd696534283d10cea793205e0e56328c4a ), feel free to clean up my mess if needed;)

**Comment by lentinj** [comment]
I'm nervous at changing the definition of open_ended at this stage, as the commits seem to. The decision is which of the following an "open_ended = upper" grouping of ``c(0,10,20,30)`` means:-

```
   l0        l10       l20       l30           (inf)
    :         :         :         :              :
(a) |-------->|-------->|-------->|------------->
(b) |-------->|-------->|----------------------->
``` 

If I'm understanding correctly, you prefer (b), as the 30 is then used as a fake upper bound in gadget?

Might as well make it configurable, and have a upper_inclusive/upper_exclusive or something.

**Comment by lentinj** [comment]
Thinking about it, I think (b) is what it was supposed to do when we were first discussing it. So how it's ended up being (a) I'm not sure.

**Comment by bthe** [comment]
Yes, b) is at least in-line with the gadget-speak while a) didn't create the correct aggregation file as the last group was omitted. We had the same problem with mfdb_step_interval, which did not write the last group to the aggregation file while the query had it. Both of these issues resulted in gadget discarding those entries.

**Comment by lentinj** [comment]
Okay, I've tidied this up, finally. I've stuck with (b) as above, but I've changed mfdb_step_interval, instead of going "one up" to do (b), it goes one "down", so ``mfdb_step_interval('l', 0, 30, open_ended = "upper")`` works exactly the same as above. This means equivalent calls of ``mfdb_step_interval`` and ``mfdb_interval`` generate the same grouping again.
