### ISSUE TITLE
Annual bootstrap replicates 

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#44]
I would like to propose an amendment to the bootstrap scheme which would generate the bootstrap replicates on an annual (or user defined) interval, i.e. for each year a new replicate would be generated.  The current implementation of the spatial bootstrap is such that the spatial subdivision replicate is chosen   and remains the same throughout.

**Comment by lentinj** [comment]
Annual would be reasonably easy, user-defined periods harder. Would just year be useful on it's own?For user defined periods were you imagining something like 1998--2000 has one bootstrap, then 2000--2010 has another? Or "quarterly"?

One way you could cheat and do this today is doing a query per-year, then combine with ``mfdb_concatenate_results()``, but that's going to get slow pretty quickly I suspect.

**Comment by bthe** [comment]
I was actually imagining that the user would define a fixed timestep, e.g year, quarter or month, but for almost all use cases I can think of I would use annual bootstrap. I would say a year would be useful on it's own. 

In the case of truly arbitrary periods I don't think using `mfdb_concatenate_results()`  would be such an overhead, if it is cumbersome to implement using the bootstrap routines. I would at least give this option a much lower priority.

**Comment by lentinj** [comment]
Any timestep less than a year would require regenerating and joining on both year and month, which would be painful. That said, there's nothing particularly hard about implementing it.

But if it's not that useful, it can just be ignored for now and come back to later if it's useful.

**Comment by bthe** [comment]
Let's just do an annual time-step, I think that would capture 99% of the potential utility of this.

**Comment by lentinj** [comment]
What does this mean for the area aggregation files (assuming we're bootstrapping over area for the sake of example)? Should the bootstrap groups have they year they were created in concatenated to them, e.g:-

```
1998-45G 45G01 45G02 45G02
1999-45G 45G01 45G02 45G03
2000-45G 45G03 45G03 45G02
```

...or should the aggregation file just combine the bootstraps? I suspect the former, but don't know if this will get in the way with what you're doing.

**Comment by bthe** [comment]
Hmm, as I've imagined that the area aggregation files would be the same, i.e. if you have a 2 area model the two area division would not change, only the subdivision within those areas between years.
