### ISSUE TITLE
mfdb_interval to include NA's

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#48]
It would be useful to be able to specify how to deal with NA's from MFDB when using mfdb_interval (or similar). For an example, if you want to query all maturity or length data but want to specify an age range for the aggregation attributes. Currently when specifying a range with mfdb_interval these will omit NA's, that is not always desirable.

**Comment by lentinj** [comment]
So something that works like ``mfdb_interval("len", c(10, 400, 1000), omitNA = FALSE)`` --> ``len10``, ``len400``, ``lenNA``?

**Comment by bthe** [comment]
I would rather like to be able to assign NAs to a valid length/age group, sort of analogous to include "upper" or "lower".

**Comment by lentinj** [comment]
So ``mfdb_interval("len", c(10, 400, 1000), na.group = "len400") --> len10, len400``. That should be doable.

**Comment by bthe** [comment]
That would be very useful:)

**Comment by lentinj** [comment]
@bthe have a look at:

https://github.com/mareframe/mfdb/commit/c4160b9fee7f906d2509a35af81b4ef9adc32f87

**Comment by lentinj** [comment]
6.x will fix this, when released (although it could be backported easily enough)
