### ISSUE TITLE
mfdb_sample_count does not return zeros for lengths with only one maturity_stage

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#56]
When I use ```mfdb_sample_count``` to calculate later a gadget likelihood for proportion of mature fish I do not get the zeros for lengths which have a maturity_stage but not another. For instance I can have only mature fish at large lengths, and the dataset extracted is not populated with zero immature fish for those same large lengths. I've the impression this makes a problem as those large lengths do not get considered in the likelihood data when I fit the model. Is my worry justified? Am I doing something wrong here?

```
mat.ven.com <- mfdb_sample_count(mdb, c('maturity_stage','age','length'), list(
    area            = "SD3031",
    timestep        = mfdb_timestep_quarterly,
    year            = 2008,
    sampling_type   = 'LND',
    species         = 'FVE',
    length          = mfdb_interval("len", seq(minlength, maxlength, by = dl)),
    age             = mfdb_interval("all",c(minage,maxage), open_ended = c("upper","lower")),
    maturity_stage  = mfdb_group('venimm'=1,'venmat'=5),
    data_source     = 'individual_comm_vendace'))
```

Thankful for your help as always

**Comment by bthe** [comment]
This shouldn’t affect the likelihood score as the default data value when read is 0. This means that, when data for some combination within a timestep is missing, zero will be used instead.

On 25 Jan 2019, at 11:00, Valerio Bartolino <notifications@github.com<mailto:notifications@github.com>> wrote:


When I use mfdb_sample_count to calculate later a gadget likelihood for proportion of mature fish I do not get the zeros for lengths which have a maturity_stage but not another. For instance I can have only mature fish at large lengths, and the dataset extracted is not populated with zero immature fish for those same large lengths. I've the impression this makes a problem as those large lengths do not get considered in the likelihood data when I fit the model. Is my worry justified? Am I doing something wrong here?

mat.ven.com<http://mat.ven.com> <- mfdb_sample_count(mdb, c('maturity_stage','age','length'), list(
    area            = "SD3031",
    timestep        = mfdb_timestep_quarterly,
    year            = 2008,
    sampling_type   = 'LND',
    species         = 'FVE',
    length          = mfdb_interval("len", seq(minlength, maxlength, by = dl)),
    age             = mfdb_interval("all",c(minage,maxage), open_ended = c("upper","lower")),
    maturity_stage  = mfdb_group('venimm'=1,'venmat'=5),
    data_source     = 'individual_comm_vendace'))


Thankful for your help as always

**Comment by vbartolino** [comment]
Thanks Bjarki. I did a quick check and you're absolutely right, the likelihoods are identical. The only difference that I could notice is in the plot of ```fit$stockdist``` as the observed ratio of those mature fish appear as NA rather than 1.
