### ISSUE TITLE
make a stomach likelihood with multiple species

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#60]
It may be an issue at the interface between ```mfdb``` and ```Rgadget```.
I'm trying to extract stomach data with ```mfdb_stomach_preyweightratio```to make a likelihood component including multiple species but then I'm having troubles to update the likelihood file with ```gadget_update```.

If I use
```
df <- mfdb_stomach_preyweightratio(mdb,
                       c("predator_length","prey_length","prey_species"),
                       list(year = ..., timestep = ..., area = ...,
                            predator_length = mfdb_interval("len",c(80,120,180), open_ended=F),
                            prey_length = mfdb_interval("len", c(1,12,35), open_ended=F),
                            prey_species = mfdb_group('vendace'='FVE',
                                                      'herring'='HER'),
                            data_source="seal_stomachs"))[[1]]
```
The extra column ```prey_species``` is problematic for ```gadget_update```:
```
Error in compare_cols(names(data), c("year", "step", "area", "predator_length",  : 
  gadget_stomachcontent_component expects data to have columns 'year,step,area,predator_length,prey_length,ratio', not 'year,step,area,predator_length,prey_length,prey_species,ratio'
```
Moreover, I would have problem with the argument ```prey_labels``` because I've more than one specie.

If I extract the two species separately:
```
df1 <- mfdb_stomach_preyweightratio(mdb,
                       c("predator_length","prey_length"),
                       list(year = ..., timestep = ..., area = ...,
                            predator_length = mfdb_interval("len",c(80,120,180), open_ended=F),
                            prey_length = mfdb_interval("len", c(1,12,35), open_ended=F),
                            prey_species = mfdb_group('vendace'='FVE'),
                            data_source="seal_stomachs"))[[1]]
df2 <- mfdb_stomach_preyweightratio(mdb,
                       c("predator_length","prey_length"),
                       list(year = ..., timestep = ..., area = ...,
                            predator_length = mfdb_interval("len",c(80,120,180), open_ended=F),
                            prey_length = mfdb_interval("len", c(1,12,35), open_ended=F),
                            prey_species = mfdb_group('herring'='HER'),
                            data_source="seal_stomachs"))[[1]]
df <- rbind(df1,df2)
attributes(df)$prey_length <- RCurl:::merge.list(attributes(df1)$prey_length, attributes(df2)$prey_length)
```
I've problems with the attributes. I've tried also to merge those but still having issue in creating a single likelihood component with ```gadget_update```
```
Error in read_component_header(fh) : Reached EOF! Shouldn't do here
```
plus the argument ```prey_labels``` remains an issue.

Thank you in advance for any suggestion

**Comment by vbartolino** [comment]
I think I've solved somehow part of the issue as follows:

- I extract the data for each species separately
- merge those into one data.frame
- fix the attributes ad hoc (although it would be nice to have a better solution) to have an extraction that is well accepted by ```gadget_update```.

At this point the remained issue is with the argument ```prey_labels``` in ```gadget_update```. I move this to ```Rgadget```

**Comment by lentinj** [comment]
This is starting to ring vague bells. We made ``mfdb_concatenate_results()`` to solve this. Does the following work?

```
df1 <- mfdb_stomach_preyweightratio(mdb,
                       c("predator_length","prey_length"),
                       list(year = ..., timestep = ..., area = ...,
                            predator_length = mfdb_interval("len",c(80,120,180), open_ended=F),
                            prey_length = mfdb_interval("vendance", c(1,12,35), open_ended=F),
                            prey_species = c('FVE'),
                            data_source="seal_stomachs"))
df2 <- mfdb_stomach_preyweightratio(mdb,
                       c("predator_length","prey_length"),
                       list(year = ..., timestep = ..., area = ...,
                            predator_length = mfdb_interval("len",c(80,120,180), open_ended=F),
                            prey_length = mfdb_interval("herring", c(1,12,35), open_ended=F),
                            prey_species = c('HER'),
                            data_source="seal_stomachs"))
df <- mfdb_concatenate_results(df1,df2)
```

...note that ``prey_length`` will be ``vendance1``, ``herring12``, etc., not just ``len12``, so the prey_length column is a reasonable prey_label. ``gadget_stomachcontent_component()`` will use the mfdb groupings here as a default, so you no longer need to supply prey_length to ``gadget_stomachcontent_component()``, just labels and coefficients.

I should add an example showing how this works before I forget again :)

I think the reason that ``gadget_stomachcontent_component()`` doesn't support something like your first query is that then the length groups used would be the same across species, which generally wouldn't make much sense.

**Comment by vbartolino** [comment]
Super thanks! I think ```mfdb_concatenate_results``` was the function I was really missing here, I can see that it preserve all the attributes of the two data.frames
