### ISSUE TITLE
dplyr functions complain about the use of select_

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#62]
Whenever I use `mfdb_dplyr_sample` R complains:

> Warning message:
>`select_()` is deprecated as of dplyr 0.7.0.
> Please use `select()` instead.

**Comment by lentinj** [comment]
Should be fixed with: https://github.com/mareframe/mfdb/commit/e42cb48ce2f87d399cad3d3f881f1f82ef5dba8f
