### ISSUE TITLE
Imports taxonomy trips on '?'

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#66]
For reasons unknown our scientists left question marks in the trip label for some of our scientific cruises from the 60's. Which causes a mild nuisance when importing the trip taxonomy, e.g:

```
mfdb_import_taxonomy(name = tibble(name = 'M?-67'))
``` 
thows an error:

```
Error: Failed to fetch row: ERROR:  new row for relation "trip" violates check constraint "trip_name_check"
```
Removing question mark this is simple enough but I will need to make sure that it is also done also when importing the tows.

**Comment by lentinj** [comment]
This name check was also annoying me with sqlite (It's the only part of the schema that doesn't work in both). I'll dig around to see if there's any reasons left for it.

My first guess was to allow for name to become an LTREE (a postgres tree structure that's delimited with ``.``), but that obviously never happened.

**Comment by lentinj** [comment]
Yup. https://github.com/gadget-framework/mfdb/commit/f7ba127167c0e116163969e31d2fb6d4847a1472

Given that ``t_group`` has since been added to make a 1-level hierarchy, and never needed to go full LTREE, this check is pretty redundant and should just be removed.

**Comment by lentinj** [comment]
It's gone now, which should make your life easier :)
