### ISSUE TITLE
Importing tow taxonomy

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#67]
I thought this had been fixed, I'm importing sample tows (which has 276901 entries) and right after that logbook tows (nrows >> than 276901 ) and I get this error: 
```
2021-03-02 11:08:50 INFO:mfdb:Taxonomy tow needs updating
2021-03-02 11:10:32 WARNING:mfdb:Rolling back transaction...
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  duplicate key value violates unique constraint "tow_pkey"
DETAIL:  Key (tow_id)=(276902) already exists.
)
```

**Comment by lentinj** [comment]
Should have been fixed with this: https://github.com/gadget-framework/mfdb/commit/17d6ee6f8c233d657619ea68e051b4ace635d2fa

Even if you didn't upgrade to 7.x, you should still have it.

**Comment by bthe** [comment]
Yes, I should have mentioned that I was working with version 7.x.

**Comment by lentinj** [comment]
This presumably isn't the same data as before, so I'm going to bug you with the previous questions: Do the dataset(s) have ID columns? Without duplicates?

I've pushed some extra debug statements to help figure this out, you can see the output if you do ``logging::setLevel('DEBUG')``.

**Comment by bthe** [comment]
Yes, this is the same dataset as before, and when I reordered the upload the tow taxonomy was updated without a hitch. It was however dreadfully slow, which may be related to the size of the data (6.6 million) but suspect most of the time goes into checking the data. 

I'll update and try again with the logging enabled.

**Comment by lentinj** [comment]
> when I reordered the upload the tow taxonomy was updated without a hitch

So you sorted the logbook tows, and the upload above worked? Sorted by what?

> It was however dreadfully slow

IIRC it's the comparing the existing and new data sets to pick out duplicates that is taking time, although it's probably worth switching to bulk copy if there's this may logbook entries to insert.

**Comment by bthe** [comment]
I uploaded the logbook data first and then the sample data after that. The tow names are based on unique keys from respective sources, so bulk upload would make a lot of sense.

**Comment by lentinj** [comment]
I've rewritten ~~(but not pushed)~~ the import to use bulk copy:

```
> s <- read.csv('logb_stations.csv')
> print(system.time(mfdb_import_tow_taxonomy(mdb, s)))
   user  system elapsed
 61.116   0.904 243.185
> s <- read.csv('stations.csv')
> print(system.time(mfdb_import_tow_taxonomy(mdb, s)))
   user  system elapsed
  2.367   0.020  18.935
```

...still not reproducing the error as before, but at least it's faster at not doing so :) ~~Will tidy up loose ends and push.~~ (done now, below)
