### ISSUE TITLE
Operations with columns in database

### ISSUE THREAD

**Issue by mmrinconh** [mareframe/mfdb#7]
Hi, I need to add a number to all the elements in the column month for all my data, can I do that easily with MFDB?

**Comment by bthe** [comment]
Just to add to this, Gadget assumes that the age is updated at the last timestep of the modelled year. And usually we assume that a year is defined in terms of a almanac year. Now for a short lived species, such as Anchovies which only live around 1.5 years, it could be useful to transform the temporal scale such that the year starts around the time the spawning occurs, not at the almanac year.

**Comment by lentinj** [comment]
@mmrinconh do you mean before inputting data, or after querying mfdb? It'd be pretty easy with some R either way, if you show some code I can give an example.

**Comment by mmrinconh** [comment]
after querying! For example I just want to add 3 to all the month column

**Comment by lentinj** [comment]
So something like this should do the trick:-

```
aggdata <- mfdb_sample_count(mdb, ...) # Or whatever your query is.
aggdata[0]$step <- aggdata[0]$step + 3
```

... then write it out to your gadget file as-per usual.
