### ISSUE TITLE
Why `t_group` has to be `%in% name` in `mfdb_import_*_taxonomy`?

### ISSUE THREAD

**Issue by MikkoVihtakari** [mareframe/mfdb#70]
I noticed a feature which purpose I don't quite understand. It appears that the `t_group` column is meant as a helper for higher-level aggregation (for example "trawls", "seines", etc.). It also appears that the names of `t_group` values are sampled from the values in `name` column. This seems like a weird design decision to me. What if I have names "bottom trawl" and "pelagic trawl" and both are in `t_group` "trawls"? Currently, MFDB does not seem to allow this.

``` r
library(mfdb)
library(tidyverse)

mfdb("test", destroy_schema = TRUE) # Delete 'test' in database for a fresh start
#> 2021-03-16 09:38:05 INFO:mfdb:Schema test removed, connect again to repopulate DB.

mdb <- mfdb("test")
#> 2021-03-16 09:38:05 INFO:mfdb:No schema, creating test
#> 2021-03-16 09:38:05 INFO:mfdb:Creating schema from scratch
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy case_study needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy institute needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy gear needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy vessel_type needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy market_category no updates to make
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy sex needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy maturity_stage needs updating
#> 2021-03-16 09:38:05 INFO:mfdb:Taxonomy species needs updating
#> 2021-03-16 09:38:06 INFO:mfdb:Taxonomy stomach_state needs updating
#> 2021-03-16 09:38:06 INFO:mfdb:Taxonomy digestion_stage needs updating
#> 2021-03-16 09:38:06 INFO:mfdb:Taxonomy index_type needs updating
#> 2021-03-16 09:38:06 INFO:mfdb:Creating indexes

mfdb_empty_taxonomy(mdb, "gear") # delete gear information
#> <PostgreSQLResult>
tbl(mdb$db, "gear") %>% collect()
#> # A tibble: 0 x 0


dt <- data.frame(gear_id = 1:4, name = as.character(1:4), t_group = rep(1:2, 2))

mfdb_import_gear_taxonomy(mdb, dt)
#> 2021-03-16 09:38:06 INFO:mfdb:Taxonomy gear needs updating
tbl(mdb$db, "gear") %>% collect() # works
#> # A tibble: 4 x 7
#>   gear_id name  t_group description mesh_size mesh_size_min mesh_size_max
#>     <int> <chr> <chr>   <chr>           <dbl>         <dbl>         <dbl>
#> 1       1 1     1       <NA>               NA            NA            NA
#> 2       2 2     2       <NA>               NA            NA            NA
#> 3       3 3     1       <NA>               NA            NA            NA
#> 4       4 4     2       <NA>               NA            NA            NA


mfdb_empty_taxonomy(mdb, "gear") # delete gear information
#> <PostgreSQLResult>
tbl(mdb$db, "gear") %>% collect()
#> # A tibble: 0 x 0

dt <- data.frame(gear_id = 1:4, name = as.character(1:4), t_group = rep(c(letters[1:2]), 2))

mfdb_import_gear_taxonomy(mdb, dt) # Does not work
#> 2021-03-16 09:38:06 INFO:mfdb:Taxonomy gear needs updating
#> 2021-03-16 09:38:06 WARNING:mfdb:Rolling back transaction...
#> Error in postgresqlExecStatement(conn, statement, ...): RS-DBI driver: (could not Retrieve the result : ERROR:  insert or update on table "gear" violates foreign key constraint "gear_t_group_fkey"
#> DETAIL:  Key (t_group)=(a) is not present in table "gear".
#> )
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by lentinj** [comment]
``t_group`` is forming 2-level tree, entries in ``t_group`` point to the parent of a child (and parents point to themselves, which is a bit odd I admit). So with you example above you need to include the parents explicitly:

```
dt <- data.frame(name = c(as.character(1:4), 'a', 'b'), t_group = rep(c(letters[1:2]), 3))
mfdb_import_gear_taxonomy(mdb, dt)
```

Your trawls example would be:

```
mfdb_import_gear_taxonomy(mdb, data.frame(
    name=c("trawls", "bottom trawl", "pelagic trawl"),
    t_group = c("trawls", "trawls", "trawls")))
```

This means the parent has it's own ID, which means life is much easier when trying to query by just "trawls".

Does this help?

aside: Setting ``gear_id = 1:4`` is the default anyway, so isn't necessary. But it's something that's snuck in from an example somewhere and stayed...

**Comment by MikkoVihtakari** [comment]
Yes, thanks! Perhaps not the simplest system for the user but you probably have your reasons :)

Perhaps add "Must be composed of values in \code{name}" to line 60 here: https://github.com/gadget-framework/mfdb/blob/6.x/man/mfdb_import_taxonomy.Rd

Pull request: https://github.com/gadget-framework/mfdb/pull/71

**Comment by MikkoVihtakari** [comment]
Eh, how would I extract data from the database by `t_group`? `mfdb_sample_totalweight(mdb, NULL, list(t_group = "trawls"))`?

**Comment by MikkoVihtakari** [comment]
> Eh, how would I extract data from the database by `t_group`? `mfdb_sample_totalweight(mdb, NULL, list(t_group = "trawls"))`?

Seems like `mfdb_sample_totalweight(mdb, NULL, list(gear = "trawls"))` does the job.

**Comment by lentinj** [comment]
Exactly, you beat me to it :)
