### ISSUE TITLE
Regular expressions to filter data?

### ISSUE THREAD

**Issue by MikkoVihtakari** [mareframe/mfdb#72]
I can do:

```
mfdb_dplyr_sample(mdb) %>%
  filter(grepl("^1|^5|61", gear) & sampling_type == "LND") %>%
  group_by(year) %>%
  summarise(total_weight = sum(weight)) %>%
  collect() %>%
  arrange(year)


# A tibble: 16 x 2
    year total_weight
   <int>        <dbl>
 1  2005     4641987 
 2  2006     4176159.
 3  2007     3460043.
 4  2008     3488820 
 5  2009     2883534 
 6  2010     2093584.
 7  2011     2511812.
 8  2012     2944629.
 9  2013     3360057.
10  2014     3588000.
11  2015     3677560.
12  2016     4454274.
13  2017     4693488.
14  2018     5290816.
15  2019     5224096.
16  2020     5189722.
```

Is it possible to do this using the gadget aggregation functions? i.e. something like:

```
mfdb_sample_totalweight(mdb, NULL,
                        list(gear = "^1|^5|61",
                             sampling_type = "LND",
                             year = 2005:2020
                        )
)
```

Does not seem to work. I can't figure out where to stuff the logical vector...

**Comment by lentinj** [comment]
No direct way I'm afraid. There was vague talk about a ``mfdb_like`` aggregate function which would have let you do this, certainly possible to do but never happened.

You could provide a list of gear names with ``grep(..., value = TRUE)`` though, but not as neat.

**Comment by MikkoVihtakari** [comment]
Ok, probably not worth using too much time on this since the `t_group` can be used for the same purpose (but not as flexibly). I'll close and mark as feature request (those never get implemented anyway :P)

**Comment by MikkoVihtakari** [comment]
Actually, this feature would be handy for negating selection. Say I have gear names `1:99` and want to select everything except `10:19`. With regular expressions, I could do it as `!grepl("^1\\d", 1:99)`. 

How would I do this in mfdb? `as.character(c(1:9, 20:99))`?

**Comment by MikkoVihtakari** [comment]
`grep("^1\\d", 1:99, invert = TRUE, value = TRUE)` works.
