### ISSUE TITLE
start and end port id's not translated in mfdb_dplyr_table

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#75]
We are starting to use the trip taxonomy to investigate travel distances and we have noticed that `mfdb_dplyr_table` does not lookup `start_port_id` and `end_port_id` from the `port` table. Any good solutions to this?

**Comment by lentinj** [comment]
Agh, I didn't think to add the recursive links here. Shouldn't be a major problem to sort though.

**Comment by lentinj** [comment]
That was fiddlier than I thought, but should work now. In the process I've changed to dbplyr 2.0 syntax, so you may need to upgrade if you haven't already.

**Comment by bthe** [comment]
This works as expected
