### ISSUE TITLE
mfdb_sample_totalweight() summarises wrong if both weight and count are available

### ISSUE THREAD

**Issue by MikkoVihtakari** [mareframe/mfdb#78]
I noticed rather peculiar behaviour in `mfdb_sample_totalweight()`. Pretty sure this is a bug, not a feature (could be a user problem, though). 

```r
library(mfdb)

mfdb(schema_name = "~/Desktop/test.duckdb", destroy_schema = TRUE)
mdb <- mfdb("~/Desktop/test.duckdb")

mfdb_import_area(mdb, data.frame(id = 1, name = 1, division = 1))

dt <- data.frame(year = c(1995, 1996), 
                 month = 1:1, 
                 areacell = 1:1, 
                 length = c(21, 54), 
                 weight = c(3,2))

mfdb_import_survey(mdb, dt)

## Correct:

mfdb_sample_totalweight(
  mdb, cols = c("length"), 
  params = list()
)

# $`0.0.0.0`
#  year step area length total_weight
# 1  all  all  all    all            5

## Wrong:

mfdb_import_survey(mdb, cbind(dt, count = c(6,5)))

mfdb_sample_totalweight(
  mdb, cols = c("length"), 
  params = list()
)

# $`0.0.0.0`
#  year step area length total_weight
# 1  all  all  all    all           28
```

Tested using the CRAN and current GitHub main branch versions on Mac OS. I fail to find where this weird summation comes from, however:

```r
library(tidyverse)
mfdb_dplyr_sample(mdb) %>% collect() %>% dplyr::select(where(~sum(!is.na(.x)) > 0))
# A tibble: 2 × 7
#   year month length weight count areacell data_source   
#   <int> <int>  <dbl>  <dbl> <dbl> <chr>    <chr>         
# 1  1995     1     21      3     6 1        default_sample
# 2 1996     1     54      2     5 1        default_sample
```

I find `mfdb_sample_totalweight()` from here https://github.com/gadget-framework/mfdb/blob/a48fb039221452b9e2fe09b0e7605e1852370497/R/mfdb_queries.R, but cannot find `mfdb_sample_grouping()`, which is probably behind this behavior.

Can you reproduce the problem?

**Comment by MikkoVihtakari** [comment]
I see now that weight column is multiplied by count. Hence the weird result. In this case weight is biomass survey index, while count is abundance survey index. They should not be multiplied. Any way to import survey indices with lengths (i.e. superindividuals) to the database?

I think I used sample because I copied some Bjarki's old scripts. Maybe there is a better way to do this now?

**Comment by lentinj** [comment]
Yes, mixing 2 separate survey indices together like that seems a bit odd. You could do something like this to prevent that:

```
mdb <- mfdb(tempfile(fileext = '.duckdb'))

mfdb_import_area(mdb, data.frame(id = 1, name = 1, division = 1))

mfdb_import_survey(mdb, data.frame(                 
                 year = c(1995, 1996), 
                 month = 1:1, 
                 areacell = 1:1, 
                 length = c(21, 54), 
                 weight = c(3,2)), data_source = 'biomass_survey')

mfdb_import_survey(mdb, data.frame(
                 year = c(1995, 1996), 
                 month = 1:1, 
                 areacell = 1:1, 
                 length = c(21, 54), 
                 count = c(6,5)), data_source = 'abundance_survey')
mfdb_sample_totalweight(
  mdb, cols = c("length"), 
  params = list(data_source = 'biomass_survey')
)
```

Using ``mfdb_import_survey_index`` and ``mfdb_survey_index_total`` would be another obvious answer, but there's no length column there. This difference really should be picked apart one day, but that's not going to help you right now.

**Comment by MikkoVihtakari** [comment]
Ok, thanks. I see it was a feature, not a bug. I guess it is documented somewhere. I do not have good suggestions how to avoid others going into this trap, except that perhaps return a message when counts are multiplied by weights. It is not obvious atm.
