### ISSUE TITLE
initial condition only numbefile

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#8]
As far as I can see 'gadget_stockfile_initialconditions' can create only numerical initial stock file. Is there a plan to add normal condition and normal parametric file format?

**Comment by lentinj** [comment]
@vbartolino Can do easily enough if it's useful, however from what I understand the datafiles can't be usefully generated from the database, so left it out for now.

**Comment by bthe** [comment]
I have done this using a mixture of Rgadget and mfdb commands, see:
https://github.com/bthe/gadget-models/blob/master/08-tusk/00-data/setup-model.R
There I use
- mfdb to generate the mean length at age and the corresponding variances 
- Rgadget::gadget.options to builid a gadget-stock object, 
- edit the initial.number data.frame with the necessary formula objects + add stddev of length at age
- write to file

**Comment by lentinj** [comment]
Also, been doing some work in https://github.com/mareframe/mfdb/issues/21 to combine what mfdb and rgadget can do in one handy package.

Have a look at:-

https://github.com/bthe/rgadget/blob/master/R/gadgetstock.R
