### ISSUE TITLE
mfdb dump memory usage

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#9]
The mfdb_cs_dump appears to consume a lot of memory (~12 gb) when exporting the Icelandic case. Postgres part of the query is reasonably fast but the post processing in R both balloons in memory and is fairly slow. I assume that the same will apply to mfdb_cs_restore when I try that.

**Comment by bthe** [comment]
To continue on this issue, restoring the cs database results in a crash, where /tmp appears to be full.

mfdb_cs_restore(mdb, 'mfdb_dump.tgz')
/usr/bin/gtar: ./sample: Cannot write: No space left on device
/usr/bin/gtar: ./sampling_type: Cannot write: No space left on device
/usr/bin/gtar: ./survey_index: Cannot write: No space left on device
/usr/bin/gtar: Exiting with failure status due to previous errors
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "survey_index_pkey" for table "survey_index"
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "sample_pkey" for table "sample"
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "prey_pkey" for table "prey"
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "predator_pkey" for table "predator"
NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "division_pkey" for table "division"
Error in read.table(file = file.path(in_location, table_name), header = TRUE,  : 
  no lines available in input
In addition: Warning message:
In untar(in_location, exdir = temp_output) :
  ‘/usr/bin/gtar -zxf 'mfdb_dump.tgz' -C '/tmp/RtmpwSDsit/mfdb_cs_restore22262cc3b55'’ returned error code 2

**Comment by lentinj** [comment]
Poot. There is really very little of my own code in the way of Postgres and R in the dump case.

As for restore, if it's a tarfile it just untars it into `/tmp` first. You could get around it by untarring it into a directory of your choosing, but I wouldn't be surprised if you hit some other memory issue.

We should try and profile this more whilst I'm in Iceland.

**Comment by lentinj** [comment]
@bthe, when you were dumping, were you also dumping into a tarfile? what does `mount | grep /tmp` say about your /tmp filesystem? Is just dumping to a directory instead better (although less convenient, obviously)

**Comment by lentinj** [comment]
@bthe There's now a `5.x` branch which is nearly ready for use. The big change here is that case studies are stored in their own postgres schema within a database, so:-
- The case studies aren't restricted to "Iceland", "Baltic", can be any string
- `pg_dump` and `pg_restore` understand how to dump a single schema from a database, so there's no real need for these dump/restore commands now.
- None of the taxonomy tables are shared across schemas now, which makes life easier for changes / additions.

There's 2 main differences after upgrading:
- Data is in a different place, and the upgrade copies data from the old "public" schema to the new schema, probably in your case called "iceland". If you access the database directly you will need to switch schemas, with `SET search_path TO 'iceland'`, or refer to the schema directly, e.g. `SELECT COUNT(*) FROM iceland.sample`.
- `destroy_schema` works on an individual schema now, not the whole lot.

I'll make an announcement once I've experimented a bit more, but if you fancy giving it a go feel free.

**Comment by bthe** [comment]
This should make sharing the database a bit more straightforward, thanks.
